languageCode = "en-us"
title = "MIMIC Critical Care Database"
theme = "mimic-data"
baseurl = "http://mimic.physionet.org"
canonifyurls = "false"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-bullhorn'></i>"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = 10
    url = "/gettingstarted/"
[[menu.main]]
    name = "Tables in MIMIC"
    pre = "<i class='fa fa-columns'></i>"
    weight = 20
    url = "/mimictables/"
[[menu.main]]
    name = "Data details"
    pre = "<i class='fa fa-cog'></i>"
    weight = 30
    url = "/mimicdata/"
[[menu.main]]
    name = "Tools"
    pre = "<i class='fa fa-wrench'></i>"
    weight = 40
    url = "/tools/"
[[menu.main]]
    name = "Community"
    pre = "<i class='fa fa-group'></i>"
    weight = 50
    url = "/community/"
[[menu.main]]
    name = "Tutorials"
    pre = "<i class='fa fa-cubes'></i>"
    weight = 60
    url = "/tutorials/"
[[menu.main]]
    name = "Archive"
    pre = "<i class='fa fa-book'></i>"
    weight = 70
    url = "/archive/"
[[menu.main]]
    name = "Help"
    pre = "<i class='fa fa-life-ring'></i>"
    weight = 80
    url = "/help"
