baseurl = "http://mimic.physionet.org/"
languageCode = "en-us"
title = "MIMIC Critical Care Database"
theme = "mimic-data"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-bullhorn'></i>"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = 10
    url = "/gettingstarted/"
[[menu.main]]
    name = "MIMIC data"
    pre = "<i class='fa fa-cog'></i>"
    weight = 20
    url = "/mimicdata/"
[[menu.main]]
    name = "Tables in MIMIC"
    pre = "<i class='fa fa-columns'></i>"
    weight = 20
    url = "/mimictables/"
[[menu.main]]
    name = "Community"
    pre = "<i class='fa fa-group'></i>"
    weight = 30
    url = "/community/"
[[menu.main]]
    name = "Tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = 50
    url = "/tutorials/"
[[menu.main]]
    name = "Glossary"
    pre = "<i class='fa fa-book'></i>"
    weight = 50
    url = "/glossary/"